biome.8=nether_wastes nether
biome.81=basalt_deltas
biome.82=soul_sand_valley
biome.83=crimson_forest
biome.84=warped_forest

biome.9=the_end end
biome.40=small_end_islands
biome.41=end_midlands
biome.42=end_highlands
biome.43=end_barrens
