#if MC_VERSION >= 11300

block.10002 = tags_saplings tags_small_flowers grass short_grass fern seagrass nether_sprouts warped_roots crimson_roots wheat potatoes beetroots torchflower weeping_vines weeping_vines_plant twisting_vines twisting_vines_plant cave_vines:berries=false cave_vines_plant:berries=false sweet_berry_bush dead_bush short_dry_grass tall_dry_grass bush

block.10081 = bamboo
block.10018 = vine sugar_cane

block.10001 = water

block.10003 = lilac:half=lower tall_grass:half=lower large_fern:half=lower rose_bush:half=lower peony:half=lower tall_seagrass:half=lower

block.10004 = lilac:half=upper tall_grass:half=upper large_fern:half=upper rose_bush:half=upper peony:half=upper tall_seagrass:half=upper kelp kelp_plant

block.10005 = birch_leaves spruce_leaves acacia_leaves jungle_leaves mangrove_leaves dark_oak_leaves azalea_leaves flowering_azalea_leaves cherry_leaves pale_oak_leaves

block.10082 = oak_leaves

block.10006 = lantern:hanging=true soul_lantern:hanging=true

block.10087 = copper_lantern exposed_copper_lantern weathered_copper_lantern oxidized_copper_lantern waxed_copper_lantern waxed_exposed_copper_lantern waxed_weathered_copper_lantern waxed_oxidized_copper_lantern

block.10015 = grass_block

block.10016 = dirt coarse_dirt rooted_dirt podzol mycelium dirt_path farmland pitcher_pod pitcher_plant carrots sunflower

block.10019 = azalea flowering_azalea firefly_bush

block.10020 = torch wall_torch lantern lantern:hanging=true lantern:hanging=false campfire:lit=true jack_o_lantern candle:lit=true white_candle:lit=true orange_candle:lit=true magenta_candle:lit=true light_blue_candle:lit=true yellow_candle:lit=true lime_candle:lit=true pink_candle:lit=true gray_candle:lit=true light_gray_candle:lit=true cyan_candle:lit=true purple_candle:lit=true blue_candle:lit=true brown_candle:lit=true green_candle:lit=true red_candle:lit=true black_candle:lit=true copper_torch copper_wall_torch
block.10021 = soul_torch soul_wall_torch soul_lantern soul_campfire:lit=true
block.10022 = fire soul_fire
block.10023 = glowstone glow_lichen sculk_catalyst:bloom=true
block.10024 = sea_lantern beacon
block.10025 = shroomlight
block.10026 = redstone_torch redstone_wall_torch redstone_lamp:lit=true
block.10027 = ochre_froglight
block.10028 = verdant_froglight
block.10029 = pearlescent_froglight

block.10030 = light

block.10031 = end_rod

block.10007 = sand sandstone chiseled_sandstone cut_sandstone sandstone_slab cut_sandstone_slab smooth_sandstone sandstone_stairs sandstone_wall

block.10008 = ice blue_ice

block.10009 = red_sand red_sandstone chiseled_red_sandstone cut_red_sandstone red_sandstone_slab cut_red_sandstone_slab smooth_red_sandstone red_sandstone_stairs red_sandstone_wall pumpkin birch_planks birch_slab birch_stairs birch_log birch_wood pale_oak_planks pale_oak_slab pale_oak_stairs

block.10010 = \
    oak_planks oak_slab oak_stairs oak_log oak_wood stripped_oak_log stripped_oak_wood \
    spruce_planks spruce_slab spruce_stairs spruce_log spruce_wood stripped_spruce_log stripped_spruce_wood \
    birch_planks birch_slab birch_stairs birch_log birch_wood stripped_birch_log stripped_birch_wood \
    jungle_planks jungle_slab jungle_stairs jungle_log jungle_wood stripped_jungle_log stripped_jungle_wood \
    acacia_planks acacia_slab acacia_stairs acacia_log acacia_wood stripped_acacia_log stripped_acacia_wood \
    dark_oak_planks dark_oak_slab dark_oak_stairs dark_oak_log dark_oak_wood stripped_dark_oak_log stripped_dark_oak_wood \
    cherry_planks cherry_slab cherry_stairs cherry_log cherry_wood stripped_cherry_log stripped_cherry_wood \
    mangrove_planks mangrove_slab mangrove_stairs mangrove_log mangrove_wood stripped_mangrove_log stripped_mangrove_wood \
    bamboo_planks bamboo_slab bamboo_stairs bamboo_block stripped_bamboo_block bamboo_mosaic bamboo_mosaic_slab bamboo_mosaic_stairs \
    crimson_planks crimson_slab crimson_stairs crimson_stem crimson_hyphae stripped_crimson_stem stripped_crimson_hyphae \
    warped_planks warped_slab warped_stairs warped_stem warped_hyphae stripped_warped_stem stripped_warped_hyphae \
    granite granite_slab granite_stairs granite_wall diorite diorite_slab diorite_stairs diorite_wall \
    dirt_path warped_nylium crimson_nylium

block.10011 = nether_bricks cracked_nether_bricks nether_brick_stairs nether_brick_slab chiseled_nether_bricks

block.10012 = \
    obsidian \
    iron_block gold_block netherite_block raw_iron_block raw_gold_block raw_copper_block \
    copper_block chiseled_copper copper_door copper_trapdoor cut_copper_slab cut_copper_stairs cut_copper copper_grate \
    waxed_copper_block waxed_chiseled_copper waxed_copper_door waxed_copper_trapdoor waxed_cut_copper_slab waxed_cut_copper_stairs waxed_cut_copper waxed_copper_grate \
    exposed_copper exposed_chiseled_copper exposed_copper_door exposed_copper_trapdoor exposed_cut_copper_slab exposed_cut_copper_stairs exposed_cut_copper exposed_copper_grate \
    waxed_exposed_copper waxed_exposed_chiseled_copper waxed_exposed_copper_door waxed_exposed_copper_trapdoor waxed_exposed_cut_copper_slab waxed_exposed_cut_copper_stairs waxed_exposed_cut_copper waxed_exposed_copper_grate \
    weathered_copper weathered_chiseled_copper weathered_copper_door weathered_copper_trapdoor weathered_cut_copper_slab weathered_cut_copper_stairs weathered_cut_copper weathered_copper_grate \
    waxed_weathered_copper waxed_weathered_chiseled_copper waxed_weathered_copper_door waxed_weathered_copper_trapdoor waxed_weathered_cut_copper_slab waxed_weathered_cut_copper_stairs waxed_weathered_cut_copper waxed_weathered_copper_grate \
    oxidized_copper oxidized_chiseled_copper oxidized_copper_door oxidized_copper_trapdoor oxidized_cut_copper_slab oxidized_cut_copper_stairs oxidized_cut_copper oxidized_copper_grate \
    waxed_oxidized_copper waxed_oxidized_chiseled_copper waxed_oxidized_copper_door waxed_oxidized_copper_trapdoor waxed_oxidized_cut_copper_slab waxed_oxidized_cut_copper_stairs waxed_oxidized_cut_copper waxed_oxidized_copper_grate \
    minecraft:copper_bulb:lit=false minecraft:waxed_copper_bulb:lit=false minecraft:exposed_copper_bulb:lit=false minecraft:waxed_exposed_copper_bulb:lit=false \
    minecraft:weathered_copper_bulb:lit=false minecraft:waxed_weathered_copper_bulb:lit=false minecraft:oxidized_copper_bulb:lit=false minecraft:waxed_oxidized_copper_bulb:lit=false \
    copper_chest copper_bars copper_chain \
    iron_door iron_trapdoor iron_bars chain lightning_rod \
    anvil chipped_anvil damaged_anvil \
    cauldron water_cauldron lava_cauldron powder_snow_cauldron \
    hopper \
    rail powered_rail detector_rail activator_rail \
    heavy_weighted_pressure_plate light_weighted_pressure_plate \
    smithing_table bell \
    piston sticky_piston piston_head moving_piston \
    brewing_stand \
    stonecutter \
    lever tripwire_hook \
    crafter \
    purpur_block purpur_pillar purpur_slab purpur_stairs

block.10013 = diamond_block emerald_block lapis_block quartz_block quartz_slab quartz_stairs smooth_quartz quartz_pillar quartz_bricks chiseled_quartz_block quartz_slab quartz_stairs packed_ice

block.10014 = slime_block honey_block

block.10017 = \
    polished_andesite polished_andesite_slab polished_andesite_stairs \
    polished_diorite polished_diorite_slab polished_diorite_stairs polished_diorite_wall \
    polished_granite polished_granite_slab polished_granite_stairs polished_granite_wall \
    polished_basalt \
    polished_deepslate polished_deepslate_slab polished_deepslate_stairs polished_deepslate_wall \
    polished_tuff polished_tuff_slab polished_tuff_stairs polished_tuff_wall \
    polished_blackstone polished_blackstone_slab polished_blackstone_stairs polished_blackstone_wall polished_blackstone_button polished_blackstone_pressure_plate \
    polished_blackstone_bricks polished_blackstone_brick_slab polished_blackstone_brick_stairs polished_blackstone_brick_wall \
    smooth_stone smooth_stone_slab \
    dark_prismarine dark_prismarine_slab dark_prismarine_stairs prismarine_bricks prismarine_brick_slab prismarine_brick_stairs \
    white_glazed_terracotta orange_glazed_terracotta magenta_glazed_terracotta light_blue_glazed_terracotta yellow_glazed_terracotta lime_glazed_terracotta pink_glazed_terracotta gray_glazed_terracotta light_gray_glazed_terracotta cyan_glazed_terracotta purple_glazed_terracotta blue_glazed_terracotta brown_glazed_terracotta green_glazed_terracotta red_glazed_terracotta black_glazed_terracotta

block.10018 = \
    stone stone_slab stone_stairs \
    stone_bricks stone_brick_slab stone_brick_stairs stone_brick_wall \
    mossy_stone_bricks mossy_stone_brick_slab mossy_stone_brick_stairs mossy_stone_brick_wall \
    cracked_stone_bricks chiseled_stone_bricks \
    deepslate deepslate_bricks deepslate_brick_slab deepslate_brick_stairs deepslate_brick_wall \
    cracked_deepslate_bricks chiseled_deepslate deepslate_tiles deepslate_tile_slab deepslate_tile_stairs deepslate_tile_wall \
    cracked_deepslate_tiles cobbled_deepslate cobbled_deepslate_slab cobbled_deepslate_stairs cobbled_deepslate_wall \
    tuff tuff_slab tuff_stairs tuff_wall tuff_bricks tuff_brick_slab tuff_brick_stairs tuff_brick_wall \
    chiseled_tuff chiseled_tuff_bricks \
    andesite andesite_slab andesite_stairs andesite_wall \
    bricks brick_slab brick_stairs brick_wall \
    mud_bricks mud_brick_slab mud_brick_stairs mud_brick_wall \
    end_stone_bricks end_stone_brick_slab end_stone_brick_stairs end_stone_brick_wall \
    prismarine prismarine_slab prismarine_stairs prismarine_wall

block.10080 = glass glass_pane tinted_glass white_stained_glass orange_stained_glass magenta_stained_glass light_blue_stained_glass yellow_stained_glass lime_stained_glass pink_stained_glass gray_stained_glass light_gray_stained_glass cyan_stained_glass purple_stained_glass blue_stained_glass brown_stained_glass green_stained_glass red_stained_glass black_stained_glass white_stained_glass_pane orange_stained_glass_pane magenta_stained_glass_pane light_blue_stained_glass_pane yellow_stained_glass_pane lime_stained_glass_pane pink_stained_glass_pane gray_stained_glass_pane light_gray_stained_glass_pane cyan_stained_glass_pane purple_stained_glass_pane blue_stained_glass_pane brown_stained_glass_pane green_stained_glass_pane red_stained_glass_pane black_stained_glass_pane

block.10032 = sea_lantern

block.10033 = end_rod

block.10034 = glow_lichen

block.10035 = glowstone lantern redstone_lamp:lit=true

block.10036 = torch wall_torch campfire:lit=true furnace:lit=true smoker:lit=true blast_furnace:lit=true torchflower potted_torchflower

block.10037 = cave_vines_plant:berries=true cave_vines:berries=true

block.10038 = redstone_torch:lit=true redstone_wall_torch:lit=true powered_rail:powered=true activator_rail:powered=true detector_rail:powered=true repeater:powered=true comparator:powered=true observer:powered=true redstone_ore:lit=true deepslate_redstone_ore:lit=true

block.10086 = redstone_wire:power=1 redstone_wire:power=2 redstone_wire:power=3 redstone_wire:power=4 redstone_wire:power=5 redstone_wire:power=6 redstone_wire:power=7 redstone_wire:power=8 redstone_wire:power=9 redstone_wire:power=10 redstone_wire:power=11 redstone_wire:power=12 redstone_wire:power=13 redstone_wire:power=14 redstone_wire:power=15

block.10039 = lava flowing_lava lava_cauldron

block.10040 = fire magma_block shroomlight

block.10059 = minecraft:copper_bulb:lit=true minecraft:waxed_copper_bulb:lit=true
block.10060 = minecraft:exposed_copper_bulb:lit=true minecraft:waxed_exposed_copper_bulb:lit=true
block.10061 = minecraft:weathered_copper_bulb:lit=true minecraft:waxed_weathered_copper_bulb:lit=true \
    minecraft:oxidized_copper_bulb:lit=true minecraft:waxed_oxidized_copper_bulb:lit=true

block.10041 = brewing_stand

block.10042 = jack_o_lantern

block.10043 = soul_fire soul_torch soul_wall_torch soul_lantern soul_campfire:lit=true

block.10044 = beacon

block.10045 = end_portal_frame:eye=true

block.10046 = sculk sculk_vein sculk_catalyst sculk_shrieker sculk_sensor:sculk_sensor_phase=inactive sculk_sensor:sculk_sensor_phase=cooldown

block.10047 = spawner dragon_head dragon_wall_head crying_obsidian

block.10048 = sea_pickle:waterlogged=true

block.10049 = crimson_fungus warped_fungus potted_crimson_fungus potted_warped_fungus

block.10050 = candle:lit=true white_candle:lit=true orange_candle:lit=true magenta_candle:lit=true light_blue_candle:lit=true yellow_candle:lit=true lime_candle:lit=true pink_candle:lit=true gray_candle:lit=true light_gray_candle:lit=true cyan_candle:lit=true purple_candle:lit=true blue_candle:lit=true brown_candle:lit=true green_candle:lit=true red_candle:lit=true black_candle:lit=true

block.10051 = ochre_froglight

block.10052 = verdant_froglight

block.10053 = pearlescent_froglight

block.10054 = enchanting_table

block.10055 = small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster

block.10085 = amethyst_block budding_amethyst

block.10056 = calibrated_sculk_sensor:sculk_sensor_phase=inactive calibrated_sculk_sensor:sculk_sensor_phase=cooldown

block.10057 = calibrated_sculk_sensor:sculk_sensor_phase=active sculk_sensor:sculk_sensor_phase=active

block.10058 = redstone_block

block.10062 = nether_portal

block.10063 = end_portal end_gateway

block.10064 = red_stained_glass red_stained_glass_pane

block.10065 = orange_stained_glass orange_stained_glass_pane

block.10066 = yellow_stained_glass yellow_stained_glass_pane

block.10067 = brown_stained_glass brown_stained_glass_pane

block.10068 = green_stained_glass green_stained_glass_pane

block.10069 = lime_stained_glass lime_stained_glass_pane

block.10070 = blue_stained_glass blue_stained_glass_pane

block.10071 = light_blue_stained_glass light_blue_stained_glass_pane

block.10072 = cyan_stained_glass cyan_stained_glass_pane

block.10073 = purple_stained_glass purple_stained_glass_pane

block.10074 = magenta_stained_glass magenta_stained_glass_pane

block.10075 = pink_stained_glass pink_stained_glass_pane

block.10076 = black_stained_glass black_stained_glass_pane tinted_glass

block.10077 = white_stained_glass white_stained_glass_pane

block.10078 = gray_stained_glass gray_stained_glass_pane

block.10079 = light_gray_stained_glass light_gray_stained_glass_pane

# Blocks NOT in block.properties get blockId=0 and could be mistaken
block.10098 = %minecraft:mineable/pickaxe %minecraft:mineable/shovel %minecraft:mineable/axe %minecraft:mineable/hoe

block.10002 = tags_saplings tags_small_flowers grass short_grass fern seagrass nether_sprouts warped_roots crimson_roots wheat potatoes beetroots torchflower weeping_vines weeping_vines_plant twisting_vines twisting_vines_plant cave_vines:berries=false cave_vines_plant:berries=false sweet_berry_bush dead_bush short_dry_grass tall_dry_grass bush
block.10081 = bamboo
block.10018 = vine sugar_cane
block.10003 = lilac:half=lower tall_grass:half=lower large_fern:half=lower rose_bush:half=lower peony:half=lower tall_seagrass:half=lower
block.10004 = lilac:half=upper tall_grass:half=upper large_fern:half=upper rose_bush:half=upper peony:half=upper tall_seagrass:half=upper kelp kelp_plant
block.10005 = birch_leaves spruce_leaves acacia_leaves jungle_leaves mangrove_leaves dark_oak_leaves azalea_leaves flowering_azalea_leaves cherry_leaves pale_oak_leaves
block.10082 = oak_leaves
block.10015 = grass_block
block.10016 = dirt coarse_dirt rooted_dirt podzol mycelium dirt_path farmland pitcher_pod pitcher_plant carrots sunflower
block.10019 = azalea flowering_azalea firefly_bush
