#if MC_VERSION >= 11300

item.10006 = lantern soul_lantern

item.10020 = torch lantern campfire jack_o_lantern candle white_candle orange_candle magenta_candle light_blue_candle yellow_candle lime_candle pink_candle gray_candle light_gray_candle cyan_candle purple_candle blue_candle brown_candle green_candle red_candle black_candle copper_torch

item.10021 = soul_torch soul_lantern soul_campfire

item.10022 = lava_bucket fire_charge

item.10023 = glowstone glow_lichen sculk_catalyst

item.10024 = sea_lantern beacon

item.10025 = shroomlight

item.10026 = redstone_torch redstone_lamp

item.10027 = ochre_froglight

item.10028 = verdant_froglight

item.10029 = pearlescent_froglight

item.10031 = end_rod

item.10032 = sea_lantern nether_star

item.10033 = end_rod

item.10034 = glow_lichen

item.10035 = glowstone lantern redstone_lamp

item.10036 = torch campfire

item.10037 = glow_berries

item.10087 = copper_lantern exposed_copper_lantern weathered_copper_lantern oxidized_copper_lantern waxed_copper_lantern waxed_exposed_copper_lantern waxed_weathered_copper_lantern waxed_oxidized_copper_lantern

item.10038 = redstone_torch

item.10039 = lava_bucket

item.10040 = fire_charge shroomlight magma_cream

item.10041 = brewing_stand

item.10042 = jack_o_lantern

item.10043 = soul_torch soul_lantern soul_campfire

item.10044 = beacon

item.10045 = ender_eye

item.10046 = sculk sculk_vein sculk_catalyst sculk_shrieker sculk_sensor

item.10047 = spawner dragon_head crying_obsidian

item.10048 = sea_pickle

item.10049 = crimson_fungus warped_fungus

item.10050 = candle white_candle orange_candle magenta_candle light_blue_candle yellow_candle lime_candle pink_candle gray_candle light_gray_candle cyan_candle purple_candle blue_candle brown_candle green_candle red_candle black_candle

item.10051 = ochre_froglight

item.10052 = verdant_froglight

item.10053 = pearlescent_froglight

item.10054 = enchanting_table

item.10055 = small_amethyst_bud medium_amethyst_bud large_amethyst_bud amethyst_cluster

item.10058 = redstone_block

item.10059 = open_eyeblossom
