#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 02 17:41:10 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Caz-Toon_1.2.1
